# Generated by Django 4.1.3 on 2022-11-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_years_of_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="position",
            field=models.CharField(default="Chef", max_length=255),
        ),
    ]
